### ISSUE TITLE
Recalculating data and phase adding

### ISSUE THREAD

**Issue by waynetsao** [bigb8/AquaResp#1]
Hi,
I was wondering how can i recalculate the data i tested before, like if my computer accidentally turned off when i'm doing a SMR measurement, or if i forgot to save the plot image the program drawn. I've tried "log to file->firesting.txt->append data(file)" but it didn't work.
And how can i know which phase or period (flushing,wait or measurement) is this data in when i'm checking my raw data, may i possibly suggest that maybe you can add like a phase column or something like that?
Thank you so much!!

**Comment by bigb8** [comment]
Hi
I am not quite certain what the issue is.

The data from the slopes should be present in the result folders. As separate files, that should give you data from the measurement phase. The data from the other periods is not save at present. However you can calculate slopes and MO2 from that data

Otherwise, you can append data from the Summary data files in each result folder

Best regards 
Morten
